### ISSUE TITLE
About city parameter

### ISSUE THREAD

**Issue by madgrk** [billykwooten/openweather-exporter#20]
Hi Kyle. Nice Job! Thank you for sharing. 
A have a question about city parameter. It's possible to scape more than one city with this parameter?

Thank you again.
John

**Comment by billykwooten** [comment]
Yes, so in the readme it states
 ```
 City/Location in which to gather weather metrics. Separate multiple locations with | for example "New York, NY|Seattle, WA"
 ```
 
 So for example you can do "New York, NY|Seattle, WA" and it would pick up both New York and Seattle.
