### ISSUE TITLE
Feature Request: 'Forecast' option from Openweather API

### ISSUE THREAD

**Issue by Kybeer** [billykwooten/openweather-exporter#26]
Hi, is the exporter grabbing "Weather" (current/historical) or "Forecast" (days ahead) from the Openweather API?

I don't get any forecast data into my Prometheus (historical works fine). I cannot find and options for it in the Container section.

**Comment by Kybeer** [comment]
Hi @billykwooten 

Yes it would be really nice. I renamed this for 'Feature Request'

**Comment by billykwooten** [comment]
Currently not looking to add this in myself as I don't see the use for Prometheus. At least not for my usecase, however, I will look over a PR if anyone wants to add it in.
