### ISSUE TITLE
Document metrics collected by default

### ISSUE THREAD

**Issue by bck01215** [billykwooten/openweather-exporter#28]
When researching exporters it's nice to know the default metrics collected. Here's an example for [oracledb_exporter](https://github.com/iamseth/oracledb_exporter)

> Description
> 
> A [Prometheus](https://prometheus.io/) exporter for Oracle modeled after the MySQL exporter. I'm not a DBA or seasoned Go developer so PRs definitely welcomed.
> 
> The following metrics are exposed currently.
> 
>     oracledb_exporter_last_scrape_duration_seconds
>     oracledb_exporter_last_scrape_error
>     oracledb_exporter_scrapes_total
>     oracledb_up
>     ...

**Comment by billykwooten** [comment]
Resolved this with https://github.com/billykwooten/openweather-exporter/pull/29
