### ISSUE TITLE
 amd64 image missing on docker hub

### ISSUE THREAD

**Issue by rare-magma** [billykwooten/openweather-exporter#30]
Hello,
Could you please push an amd64 image of the latest release?

I've updated the container today and unfortunately can't run it on my amd64 server due to the following error:
```
WARNING: image with reference billykwooten/openweather-exporter was found but does not match the specified platform: wanted linux/amd64, actual: linux/arm64
docker: Error response from daemon: image with reference billykwooten/openweather-exporter was found but does not match the specified platform: wanted linux/amd64, actual: linux/arm64.
```
Thanks!

**Comment by billykwooten** [comment]
Hey @rare-magma! This should be fixed, this was an oversight on my part. Forgot to change the build platform during build, being on an M1 it compiled with the default arm64.

Please try now, this should be resolved and be back to normal! :)

**Comment by rare-magma** [comment]
thanks @billykwooten! I've tested it now and it's working as expected.
