### ISSUE TITLE
Don't see any rain

### ISSUE THREAD

**Issue by gmueller2000privat** [billykwooten/openweather-exporter#40]
The current version seems not to deliver any rain values.  Here in Bavaria (Roth, DE) we are having a lot of rain these days but the exporter always tells me 0 rain.

**Comment by billykwooten** [comment]
Hey @gmueller2000privat, I just moved the API to 3.0, could you test again and re-open a ticket if the problem is still occuring?

**Comment by gmueller2000privat** [comment]
Sorry for the late feedback but wanted to wait for rain and snow. Both are working great now. Thanks!
