### ISSUE TITLE
Forecast data?

### ISSUE THREAD

**Issue by GideonWolfe** [billykwooten/openweather-exporter#44]
There seems to be quite a few fields that are available to OWM that aren't exported by this tool. Specifically how feasible would it be to get fields like `daily.summary` could be used to build dashboards that can forecast weather

**Comment by billykwooten** [comment]
Hey @GideonWolfe, right now I have no plans to implement forecasting into this tool as it's meant for prometheus and mainly integers/quantiles. Forecasting is more data-based information, which i'm not sure fits this toolset.

However, if someone wants to experiment with that i'm happy to look over a pull request.
