### ISSUE TITLE
Option to fallback to previous API versions

### ISSUE THREAD

**Issue by hundredfire** [billykwooten/openweather-exporter#46]
Since ver 0.0.12, api 3.0 subscription is required. Therefore, API calls fail with error 401 since update. Checking on openweathermap's website, the only way to subscribe for this api version still requires users to provide bank card infos, even if you plan to stay in the limits of their free calls allowances.
I'm sure many users would feel uncomfortable giving their banking infos to owm, like me. Would it be possible to add a flag in the container to continue using api 2.0/2.5 instead (with limited capabilities if needed?)

Thank you for your work

**Comment by idhirandar** [comment]
or now its time to move to another free API server like WeatherAPI.com, Forecast, Meteostat, Weather Embed,

**Comment by billykwooten** [comment]
Hey guys, currently I have no interest to move to another solution as this one works fine for now.

However, if you'd like to continue using the old 2.5 API, I would just stick with v0.0.11 of this container [HERE](https://github.com/billykwooten/openweather-exporter/releases/tag/v0.0.11). I don't see a need to code a fallback option when that v0.0.11 only supports 2.5 in the first place and with it's pending deprication i'm not sure the effort warrants the time.

**Comment by lomereiter** [comment]
For the record, the 2.5 API will be gone in June 2024: https://openweathermap.org/one-call-transfer

If you are worried about potential charges, you can set the daily limit on OWM side: 
![image](https://github.com/billykwooten/openweather-exporter/assets/662555/91e2e6c9-a483-40f2-8510-e3aeabf78303)
